# Generated by Django 5.0.3 on 2024-03-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('patrimonio', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_maquina', to='inventory.maquina')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_marca', to='inventory.marca')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_monitor', to='inventory.monitor')),
            ],
        ),
    ]
