# Generated by Django 5.0.3 on 2024-03-14 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='name',
        ),
        migrations.AddField(
            model_name='maquina',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itens',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_setor', to='inventory.maquina'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_marca', to='inventory.marca'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_monitor', to='inventory.monitor'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='itens',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_maquina', to='inventory.setor'),
        ),
    ]
