# Generated by Django 5.0.3 on 2024-04-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorycontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='inventory_manager/'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itens',
            name='serie',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
