# Generated by Django 5.0.3 on 2024-04-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itens_arquivo_alter_itens_patrimonio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='inventory/'),
        ),
    ]
